# Generated by Django 2.1.3 on 2018-11-21 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('intro', models.CharField(max_length=300)),
                ('body', models.TextField()),
                ('image', models.FileField(upload_to='')),
                ('status', models.CharField(choices=[('PUB', 'Published'), ('DRA', 'Draft')], default='DRA', max_length=3)),
            ],
        ),
    ]
