# Generated by Django 2.1.3 on 2018-11-24 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('posts', '0003_post_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='categories',
            field=models.ManyToManyField(to='categories.Category'),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('PUB', 'Published'), ('DRA', 'Draft')], default='PUB', max_length=3),
        ),
    ]
