# Generated by Django 2.1.3 on 2018-11-24 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20181124_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('PUB', 'Published'), ('DRA', 'Draft')], default='DRA', max_length=3),
        ),
    ]
