# Generated by Django 2.1.3 on 2018-11-24 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_auto_20181124_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(blank=True, choices=[('PUB', 'Published'), ('DRA', 'Draft')], max_length=3),
        ),
    ]
