# Generated by Django 2.1.3 on 2018-11-24 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_auto_20181124_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('PUB', 'Published'), ('DRA', 'Draft')], default='PUB', max_length=3),
        ),
    ]
