# Generated by Django 2.1.3 on 2018-11-25 11:22

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blogs', '0002_auto_20181125_1209'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserBlog',
            new_name='Blog',
        ),
    ]
