# Generated by Django 2.1.3 on 2018-11-26 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_auto_20181125_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='username',
            field=models.CharField(default=2, max_length=20),
            preserve_default=False,
        ),
    ]
